db:
  image: postgres:12.0-alpine
  restart: always
  environment:
    - POSTGRES_RANDOM_ROOT_PASSWORD=yes
    - POSTGRES_DB=app
    - POSTGRES_USER=app
    - POSTGRES_PASSWORD=pass
  ports:
    - '5432:5432'
nodejs:
  build: ./gate-simulator
  ports:
    - '9999:9999'